#!/usr/bin/env python3
"""
Katakana -> English for the charme-du-vin アメリカ category.

Separate table again, for the same reason the Iberian one is separate:
シャルドネ is Chardonnay everywhere, but ヴィーニャ / カステロ / リザーヴ do not
mean the same thing across catalogues, and a US "Reserve" is not an Italian
"Riserva".

US names are English underneath, which makes a phonetic guess tempting and
wrong -- キスラー is Kistler, not "Kisler", and シンクアノン is Sine Qua Non.
Rule 3 still holds: anything not listed here is left as-is and flagged, and
the unconverted list is reported rather than filled in by ear.
"""

from __future__ import annotations

from italia_lexicon import convert as _convert

LEXICON: dict[str, tuple[str, str]] = {
    # ---- producers -------------------------------------------------------
    "キスラー": ("Kistler", "키슬러"),
    "キスラーヴィニヤード": ("Kistler Vineyard", "키슬러 빈야드"),
    "カレラ": ("Calera", "칼레라"),
    "オクシデンタル": ("Occidental", "옥시덴탈"),
    "オクシデンダル": ("Occidental", "옥시덴탈"),
    "ジョセフフェルプス": ("Joseph Phelps", "조셉 펠프스"),
    "コングスガード": ("Kongsgaard", "콩스가드"),
    "オーベール": ("Aubert", "오베르"),
    "シェーファー": ("Shafer", "셰이퍼"),
    "オーボンクリマ": ("Au Bon Climat", "오 봉 클리마"),
    "シルヴァーオーク": ("Silver Oak", "실버 오크"),
    "ボーグル": ("Bogle", "보글"),
    "フランシスコッポラ": ("Francis Ford Coppola", "프란시스 코폴라"),
    "ドミナス": ("Dominus", "도미누스"),
    "ピーターマイケル": ("Peter Michael", "피터 마이클"),
    "パルメイヤー": ("Pahlmeyer", "팔마이어"),
    "クロデュヴァル": ("Clos du Val", "클로 뒤 발"),
    "シンクアノン": ("Sine Qua Non", "신 쿠아 논"),
    "シンクワノン": ("Sine Qua Non", "신 쿠아 논"),
    "ジョエルゴット": ("Joel Gott", "조엘 고트"),
    "ゴット": ("Gott", "고트"),
    "ブレッド&バター": ("Bread & Butter", "브레드 앤 버터"),
    "オーパスワン": ("Opus One", "오퍼스 원"),
    "オーヴァチュア": ("Overture", "오버추어"),
    "ワイバイヨシキ": ("Y by Yoshiki", "와이 바이 요시키"),
    "ヨシキ": ("Yoshiki", "요시키"),
    "スポッツウッド": ("Spottswoode", "스팟츠우드"),
    "ヴェリテ": ("Vérité", "베리테"),
    "ヴァリテ": ("Vérité", "베리테"),
    "スターレーン": ("Star Lane", "스타 레인"),
    "ラヴァンチュール": ("L'Aventure", "라방튀르"),
    "アデュレーション": ("Adulation", "애듈레이션"),
    "コスタブラウン": ("Kosta Browne", "코스타 브라운"),
    "ドルーアン": ("Drouhin", "드루앵"),
    "ドルーアンオレゴン": ("Domaine Drouhin Oregon", "도멘 드루앵 오리건"),
    "ドメーヌドルーアン": ("Domaine Drouhin", "도멘 드루앵"),
    "ジョセフドルーアン": ("Joseph Drouhin", "조셉 드루앵"),
    "ドメーヌセリーヌ": ("Domaine Serene", "도멘 세레네"),
    "アントヒルファームズ": ("Anthill Farms", "앤트힐 팜스"),
    "ロバートモンダヴィ": ("Robert Mondavi", "로버트 몬다비"),
    "グレースファミリー": ("Grace Family", "그레이스 패밀리"),
    "タリー": ("Talley", "탈리"),
    "ホール": ("Hall", "홀"),
    "クインテッサ": ("Quintessa", "퀸테사"),
    "ハンドレッドエイカー": ("Hundred Acre", "헌드레드 에이커"),
    "ジャガーナット": ("Juggernaut", "저거너트"),
    "ホースパワー": ("Horsepower", "호스파워"),
    "ベルグロス": ("Belle Glos", "벨 글로스"),
    "ベルグロ": ("Belle Glos", "벨 글로스"),
    "ウェイフェアラー": ("Wayfarer", "웨이페어러"),
    "ファヴィア": ("Favia", "파비아"),
    "デリールセラーズ": ("DeLille Cellars", "드릴 셀러스"),
    "デリールセラー": ("DeLille Cellars", "드릴 셀러스"),
    "ルイス": ("Lewis", "루이스"),
    "フラワーズ": ("Flowers", "플라워스"),
    "クレマ": ("La Crema", "라 크레마"),
    "マスコット": ("The Mascot", "더 마스코트"),
    "チョークヒル": ("Chalk Hill", "초크 힐"),
    "ケイマス": ("Caymus", "케이머스"),
    "ハーラン": ("Harlan Estate", "할란 에스테이트"),
    "プロモントリー": ("Promontory", "프로몬토리"),
    "コルギン": ("Colgin", "콜긴"),
    "コルギンセラーズ": ("Colgin Cellars", "콜긴 셀러스"),
    "マーカッサン": ("Marcassin", "마카신"),
    "イングルヌック": ("Inglenook", "잉글눅"),
    "ルビコン": ("Rubicon", "루비콘"),
    "リッジ": ("Ridge", "리지"),
    "リットンスプリングス": ("Lytton Springs", "리튼 스프링스"),
    "アローホ": ("Araujo", "아라우호"),
    "アイズリーヴィニヤード": ("Eisele Vineyard", "아이젤 빈야드"),
    "ダラヴァレ": ("Dalla Valle", "달라 발레"),
    "マヤ": ("Maya", "마야"),
    "ダブルダイヤモンド": ("Double Diamond", "더블 다이아몬드"),
    "ユリシーズ": ("Ulysses", "율리시스"),
    "トレフェッセン": ("Trefethen", "트레페던"),
    "ダックホーン": ("Duckhorn", "덕혼"),
    "デコイ": ("Decoy", "디코이"),
    "ニュートン": ("Newton", "뉴턴"),
    "ホワイトホールレーン": ("Whitehall Lane", "화이트홀 레인"),
    "ベッドロック": ("Bedrock", "베드록"),
    "ベッドロックヴィンニヤード": ("Bedrock Vineyard", "베드록 빈야드"),
    "ターリー": ("Turley", "털리"),
    "アルバン": ("Alban", "알반"),
    "タブラスクリーク": ("Tablas Creek", "타블라스 크릭"),
    "タブラス": ("Tablas", "타블라스"),
    "チャールズスミス": ("Charles Smith", "찰스 스미스"),
    "チャールズスミスワイン": ("Charles Smith Wines", "찰스 스미스 와인스"),
    "Kヴィントナーズ": ("K Vintners", "케이 빈트너스"),
    "マシューズ": ("Matthews", "매튜스"),
    "デュモル": ("DuMOL", "듀몰"),
    "ギャリーファレル": ("Gary Farrell", "게리 패럴"),
    "Jロキオリ": ("J. Rochioli", "제이 로키올리"),
    "ラホタ": ("La Jota", "라 호타"),
    "アウトポスト": ("Outpost", "아웃포스트"),
    "ジラード": ("Girard", "지라드"),
    "アローウッド": ("Arrowood", "애로우드"),
    "キャッスルロック": ("Castle Rock", "캐슬 록"),
    "マクマニスファミリー": ("McManis Family", "맥매니스 패밀리"),
    "キャノンボール": ("Cannonball", "캐논볼"),
    "テキストブック": ("Textbook", "텍스트북"),
    "ヒルト": ("The Hilt", "더 힐트"),
    "エデンリフト": ("Eden Rift", "에덴 리프트"),
    "ダットンゴールドフィールド": ("Dutton Goldfield", "더튼 골드필드"),
    "ダットンランチ": ("Dutton Ranch", "더튼 랜치"),
    "ダットン": ("Dutton", "더튼"),
    "アストンエステート": ("Aston Estate", "애스턴 에스테이트"),
    "ビーヴァンセラーズ": ("Bevan Cellars", "비반 셀러스"),
    "ジョセフカー": ("Joseph Carr", "조셉 카"),
    "フェルプスクリークヴィニヤード": ("Phelps Creek Vineyards", "펠프스 크릭 빈야드"),
    "アナベラ": ("Annabella", "아나벨라"),
    "レコル": ("L'Ecole", "레콜"),
    "イングルヌックルビコン": ("Inglenook Rubicon", "잉글눅 루비콘"),

    # ---- regions / AVAs --------------------------------------------------
    "ナパ": ("Napa", "나파"),
    "ナパヴァレー": ("Napa Valley", "나파 밸리"),
    "ソノマ": ("Sonoma", "소노마"),
    "ソノマコースト": ("Sonoma Coast", "소노마 코스트"),
    "ソノマカウンティ": ("Sonoma County", "소노마 카운티"),
    "ソノママウンテン": ("Sonoma Mountain", "소노마 마운틴"),
    "オークヴィル": ("Oakville", "오크빌"),
    "オークノール": ("Oak Knoll", "오크 놀"),
    "オークノールディストリクト": ("Oak Knoll District", "오크 놀 디스트릭트"),
    "オレゴン": ("Oregon", "오리건"),
    "カリフォルニア": ("California", "캘리포니아"),
    "アレキサンダーヴァレー": ("Alexander Valley", "알렉산더 밸리"),
    "アレキサンダー": ("Alexander", "알렉산더"),
    "ルシアンリヴァーヴァレー": ("Russian River Valley", "러시안 리버 밸리"),
    "ルシアンリヴァー": ("Russian River", "러시안 리버"),
    "ラシアンリヴァーヴァレー": ("Russian River Valley", "러시안 리버 밸리"),
    "ラシアンヴァレー": ("Russian River Valley", "러시안 리버 밸리"),
    "ロシアンリヴァー": ("Russian River", "러시안 리버"),
    "マウントハーラン": ("Mt. Harlan", "마운트 할란"),
    "ハウエルマウンテン": ("Howell Mountain", "하웰 마운틴"),
    "カーネロス": ("Carneros", "카네로스"),
    "クームスヴィル": ("Coombsville", "쿰스빌"),
    "サンタバーバラ": ("Santa Barbara", "산타 바바라"),
    "モントレー": ("Monterey", "몬터레이"),
    "クラークスバーグ": ("Clarksburg", "클락스버그"),
    "クラークスブルグ": ("Clarksburg", "클락스버그"),
    "アロヨグランデヴァレー": ("Arroyo Grande Valley", "아로요 그란데 밸리"),
    "コロンビアヴァレー": ("Columbia Valley", "컬럼비아 밸리"),
    "フリーストーン": ("Freestone", "프리스톤"),
    "ヘッドランズ": ("Headlands", "헤드랜즈"),
    "ヘッドランズヴィニヤード": ("Headlands Vineyard", "헤드랜즈 빈야드"),
    "ハイランズ": ("Highlands", "하이랜즈"),
    "ナパハイランズ": ("Napa Highlands", "나파 하이랜즈"),

    # ---- grapes ----------------------------------------------------------
    "シャルドネ": ("Chardonnay", "샤르도네"),
    "カベルネソーヴィニヨン": ("Cabernet Sauvignon", "카베르네 소비뇽"),
    "カベルネソーヴィニョン": ("Cabernet Sauvignon", "카베르네 소비뇽"),
    "カベルネ": ("Cabernet", "카베르네"),
    "ピノノワール": ("Pinot Noir", "피노 누아"),
    "ピノグリ": ("Pinot Gris", "피노 그리"),
    "メルロー": ("Merlot", "메를로"),
    "シラー": ("Syrah", "시라"),
    "プチシラー": ("Petite Sirah", "쁘띠 시라"),
    "デュリフ": ("Durif", "뒤리프"),
    "ジンファンデル": ("Zinfandel", "진판델"),
    "グルナッシュ": ("Grenache", "그르나슈"),
    "ソーヴィニヨンブラン": ("Sauvignon Blanc", "소비뇽 블랑"),
    "ソーヴィニヨン": ("Sauvignon", "소비뇽"),
    "ゲヴュルツトラミナー": ("Gewürztraminer", "게뷔르츠트라미너"),
    "ゲヴュルツトラミネール": ("Gewürztraminer", "게뷔르츠트라미너"),
    "リースリング": ("Riesling", "리슬링"),
    "アルバリーニョ": ("Albariño", "알바리뇨"),

    # ---- single vineyards / cuvées ---------------------------------------
    "インシグニア": ("Insignia", "인시그니아"),
    "ジェンセン": ("Jensen", "젠슨"),
    "セレック": ("Selleck", "셀렉"),
    "ミルズ": ("Mills", "밀스"),
    "ライアン": ("Ryan", "라이언"),
    "ドゥヴィリエ": ("de Villiers", "드 빌리에"),
    "ナパヌック": ("Napanook", "나파눅"),
    "ヒルサイドセレクト": ("Hillside Select", "힐사이드 셀렉트"),
    "レッドショルダーランチ": ("Red Shoulder Ranch", "레드 숄더 랜치"),
    "ワンポイントファイヴ": ("One Point Five", "원 포인트 파이브"),
    "ローズロック": ("Roserock", "로즈록"),
    "ニュイブランシュ": ("Nuits Blanches", "뉘 블랑슈"),
    "キュヴェエリザベス": ("Cuvée Elizabeth", "퀴베 엘리자베스"),
    "エリザベス": ("Elizabeth", "엘리자베스"),
    "キュヴェ": ("Cuvée", "퀴베"),
    "ハドソン": ("Hudson", "허드슨"),
    "ハドソンヴィニヤード": ("Hudson Vineyard", "허드슨 빈야드"),
    "ハイドヴィニヤード": ("Hyde Vineyard", "하이드 빈야드"),
    "トレントンロードハウス": ("Trenton Roadhouse", "트렌턴 로드하우스"),
    "ラームドグラップ": ("L'Âme du Grape", "람 뒤 그라프"),
    "ダイヤモンドコレクション": ("Diamond Collection", "다이아몬드 컬렉션"),
    "ディレクターズカット": ("Director's Cut", "디렉터스 컷"),
    "プライベートセレクション": ("Private Selection", "프라이빗 셀렉션"),
    "リザーヴ": ("Reserve", "리저브"),
    "リザーブ": ("Reserve", "리저브"),
    "エステート": ("Estate", "에스테이트"),
    "エステーツ": ("Estates", "에스테이츠"),
    "ヴィニヤード": ("Vineyard", "빈야드"),
    "ヴィンヤード": ("Vineyard", "빈야드"),
    "ランチ": ("Ranch", "랜치"),
    "クラレット": ("Claret", "클라레"),
    "レッドブレンド": ("Red Blend", "레드 블렌드"),
    "オールドヴァイン": ("Old Vine", "올드 바인"),
    "オールドヴァン": ("Old Vine", "올드 바인"),
    "アンフィルタード": ("Unfiltered", "언필터드"),
    "バレルエイジド": ("Barrel Aged", "배럴 에이지드"),
    "プロプリエタリーレッド": ("Proprietary Red", "프로프라이어터리 레드"),
    "プロプライエタリー": ("Proprietary", "프로프라이어터리"),
    "ロゼ": ("Rosé", "로제"),
    "ブラン": ("Blanc", "블랑"),
    "ホワイト": ("White", "화이트"),
    "レッド": ("Red", "레드"),
    "ザ": ("The", "더"),
    "ザジャッジ": ("The Judge", "더 저지"),
    "ジャッジメント": ("Judgement", "저지먼트"),
    "コート": ("Côte", "코트"),
    "ル": ("Le", "르"),
    "レ": ("Les", "레"),
    "ラ": ("La", "라"),
    "ド": ("de", "드"),
    "ア": ("A", "에이"),
}


def convert(name: str) -> dict:
    return _convert(name, LEXICON)
